Feature/actuallyzach/lcd
RIT-EVT/charge-controller pull request #2
Opened 2023-02-25 17:04 UTC by ActuallyZach

2023-03-03 04:42 UTC, mjmagee991 requested changes
A couple minor issues. Also, don't worry about reformatting anything. Once we get the autoformatter set up for this repo, most of it will get cleaned up automatically

2023-03-03 04:42 UTC, mjmagee991 commented on include/charge_controller/dev/LCDDisplay.hpp
> +    /**
Add newlines between the functions

2023-03-03 04:42 UTC, mjmagee991 commented on include/charge_controller/dev/LED.hpp
> +    class LED {
Code inside namespaces shouldn't be indented

2023-03-03 04:42 UTC, mjmagee991 commented on src/charge_controller/dev/LCDDisplay.cpp
> +    std::sprintf(batteryOneVolt, "%d v", batteryOneVoltage);
Volts use a capital V
This is quite possibly one of the nitpickiest comments I have ever left

2023-03-03 04:42 UTC, mjmagee991 commented on src/charge_controller/dev/LCDDisplay.cpp
> +}
Newline

2023-03-04 15:22 UTC, ActuallyZach commented
![](https://github.trello.services/images/mini-trello-icon.png) [Charge Controller LCD](https://trello.com/c/xwewglwV/46-charge-controller-lcd)

2023-03-04 15:28 UTC, mjmagee991 approved these changes
Nice work

2023-03-10 01:05 UTC, DeLozM8 approved these changes

2023-03-20 22:40 UTC, merged